apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dstrategies-frontend
spec:
  gateways:
  - dstrategies-frontend
  hosts:
  - dstrategies-frontend-{{ .Release.Namespace }}-istio-system.apps.{{ .Values.domain }}
  http:
  - name: primary
    route:
    - destination:
        host: dstrategies-frontend.{{ .Release.Namespace }}.svc.cluster.local
      weight: 100