apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.name" . }}-configmap-env-base
  labels:
    app.kubernetes.io/name: {{ include "service.name" . }}
    app: {{ include "service.name" . }}
data:
  application.version: {{ .Values.service.image.version }}
  quarkus.log.level: DEBUG
  quarkus.jaeger.service-name: "dstrategies-back"
  quarkus.jaeger.sampler-type: "const"
  quarkus.jaeger.sampler-param: "1"
  quarkus.jaeger.endpoint: "http://jaeger-collector.gitops.svc:14268/api/traces"
  quarkus.jaeger.propagation: "b3"
  quarkus.jaeger.reporter-log-spans: "true"
  quarkus.http.cors: 'true'
